/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: kenchoo (https://sketchfab.com/kenchoo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/black-panther-7fca11c89cca4362a525c891a8345112
Title: black panther
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useLoader } from "@react-three/fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import * as THREE from "three";
export default function BlackPanther(props) {
  const group = useRef();
  const { animations } = useGLTF("./models/black_panther.glb");
  const nodes = useLoader(GLTFLoader, "./models/black_panther.glb")["nodes"];
  const materials = useLoader(GLTFLoader, "./models/black_panther.glb")[
    "materials"
  ];
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Panther_Rig_51" scale={0.01}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={(nodes["Object_7"] as THREE.SkinnedMesh).geometry}
                    skeleton={(nodes["Object_7"] as THREE.SkinnedMesh).skeleton}
                    morphTargetDictionary={
                      (nodes["Object_7"] as THREE.SkinnedMesh)
                        .morphTargetDictionary
                    }
                    morphTargetInfluences={
                      (nodes["Object_7"] as THREE.SkinnedMesh)
                        .morphTargetInfluences
                    }
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={(nodes["Object_8"] as THREE.SkinnedMesh).geometry}
                    skeleton={(nodes["Object_8"] as THREE.SkinnedMesh).skeleton}
                    morphTargetDictionary={
                      (nodes["Object_8"] as THREE.SkinnedMesh)
                        .morphTargetDictionary
                    }
                    morphTargetInfluences={
                      (nodes["Object_8"] as THREE.SkinnedMesh)
                        .morphTargetInfluences
                    }
                  />
                  <skinnedMesh
                    name="Object_9"
                    geometry={(nodes["Object_9"] as THREE.SkinnedMesh).geometry}
                    skeleton={(nodes["Object_9"] as THREE.SkinnedMesh).skeleton}
                    morphTargetDictionary={
                      (nodes["Object_9"] as THREE.SkinnedMesh)
                        .morphTargetDictionary
                    }
                    morphTargetInfluences={
                      (nodes["Object_9"] as THREE.SkinnedMesh)
                        .morphTargetInfluences
                    }
                  />
                  <skinnedMesh
                    name="Object_10"
                    geometry={
                      (nodes["Object_10"] as THREE.SkinnedMesh).geometry
                    }
                    skeleton={
                      (nodes["Object_10"] as THREE.SkinnedMesh).skeleton
                    }
                    morphTargetDictionary={
                      (nodes["Object_10"] as THREE.SkinnedMesh)
                        .morphTargetDictionary
                    }
                    morphTargetInfluences={
                      (nodes["Object_10"] as THREE.SkinnedMesh)
                        .morphTargetInfluences
                    }
                  />
                  <skinnedMesh
                    name="Object_11"
                    geometry={
                      (nodes["Object_11"] as THREE.SkinnedMesh).geometry
                    }
                    skeleton={
                      (nodes["Object_11"] as THREE.SkinnedMesh).skeleton
                    }
                    morphTargetDictionary={
                      (nodes["Object_11"] as THREE.SkinnedMesh)
                        .morphTargetDictionary
                    }
                    morphTargetInfluences={
                      (nodes["Object_11"] as THREE.SkinnedMesh)
                        .morphTargetInfluences
                    }
                  />
                  <skinnedMesh
                    name="Object_13"
                    geometry={(nodes.Object_13 as THREE.SkinnedMesh).geometry}
                    material={materials["Material5-material"]}
                    skeleton={(nodes.Object_13 as THREE.SkinnedMesh).skeleton}
                    morphTargetDictionary={
                      (nodes.Object_13 as THREE.SkinnedMesh)
                        .morphTargetDictionary
                    }
                    morphTargetInfluences={
                      (nodes.Object_13 as THREE.SkinnedMesh)
                        .morphTargetInfluences
                    }
                  />
                  <group name="black_pather_49" />
                  <group name="tongue_50" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/black_panther.glb");
